title: Nokia 6300 4G (nokia-leo)
author: Bùi Minh Đức
# baseurl: "https://bmndc.github.io/nokia-leo/"
# description: >
#   In late 2020, following the successful relaunch of the Nokia-branded retros 2720 Flip and 800 Tough, HMD Global (then Nokia Mobile) quietly introduced the new Nokia 6300 4G to the world. It retains the classic candybar look of the original 6300, while packing features such as 4G LTE and Wi-Fi into a pocket-friendly design. At €49/$69.99, it was one of the most affordable KaiOS phones in the company's lineup, and also received criticisms from users regarding its performance and keypad.

# Favicons for other platforms are optional, but you can generate them at https://realfavicongenerator.net/
# favicon: "assets/favicon.ico"

markdown: CommonMarkGhPages

theme: no-style-please
exclude: 
  - assets/
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

theme_config:
  appearance: "auto" # 'auto' switches between light and dark depending on device's color scheme; other options: 'light', 'dark'
  back_home_text: "&larr; Back to main page" # Customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # Date format for posts, %d for day, %m for month, %Y for year
  show_description: false # Choose to whether to show page description under the homepage title

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]