title: Nokia 6300 4G (nokia-leo)
author: Bùi Minh Đức
description: >
  Archive of guides, source code and firmware backups for Nokia 6300 4G.

favicon: "assets/img/banana.png"

markdown: CommonMarkGhPages

theme: no-style-please
exclude: 
  - root.sh
  - fota.sh
  - curef.json
  - 8k.mbn
  - recovery-8110.img
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

theme_config:
  appearance: "auto"
  back_home_text: "Back to main page"
  date_format: "%d-%m-%Y"
  show_description: false

commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]