title: Nokia 6300 4G (nokia-leo)
author: Bùi Minh Đức
url: https://wiki.bananahackers.net
description: >
  Archive of guides, source code and firmware backups for Nokia 6300 4G.

favicon: "img/banana.png"

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto"
  back_home_text: "Back to main page"
  date_format: "%d-%m-%Y"
  show_description: false

plugins:
  - jekyll-seo-tag