title: Nokia 6300 4G (nokia-leo)
author: Bùi Minh Đức
description: >
  Archive of guides, source code and firmware backups for Nokia 6300 4G.

favicon: "assets/img/banana.png"

markdown: gfm

theme: no-style-please
exclude: [root.sh, fota.sh, curef.json, 8k.mbn, recovery-8110.img]

theme_config:
  appearance: "auto"
  back_home_text: "Back to main page"
  date_format: "%d-%m-%Y"
  show_description: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag