$inherits:
  from: 'tasks/builds/b2g_phone_eng_base.yml'
  variables:
    build_name: 'flame-kk-eng'
    build_type: 'opt'
task:
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-flame-kk-eng'
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-flame-kk-eng-objdir-gecko'
  metadata:
    name: '[TC] B2G Flame KK Eng'

  payload:
    cache:
      level-{{level}}-{{project}}-build-flame-kk-eng: /home/worker/workspace
      level-{{level}}-{{project}}-build-flame-kk-eng-objdir-gecko: /home/worker/objdir-gecko
    env:
      TARGET: 'flame-kk'
  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      symbol: Be
      groupSymbol: Flame-KK
      groupName: Flame KitKat Device Image
      machine:
        platform: b2g-device-image
    locations:
      img: 'private/build/flame-kk.zip'
