---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/branches/base_job_flags.yml

$inherits:
  from: tasks/branches/base_jobs.yml

# Flags specific to this branch
flags:
  post-build:
    - upload-symbols

builds:
  emulator-x86-l:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_x86_l_opt.yml
  android-api-15:
    platforms:
      - Android
    types:
      opt:
        task: tasks/builds/android_api_15.yml
  android-partner-sample1:
    platforms:
      - Android
    types:
      opt:
        task: tasks/builds/android_api_15_partner_sample1.yml
  linux:
    platforms:
      - Linux
    types:
      opt:
        task: tasks/builds/opt_linux32.yml
      debug:
        task: tasks/builds/dbg_linux32.yml
  linux64:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/opt_linux64.yml
      debug:
        task: tasks/builds/dbg_linux64.yml
  linux64-st-an:
    platforms:
      - Linux64 Static Analysis
    types:
      opt:
        task: tasks/builds/opt_linux64_st-an.yml
  linux64-haz:
    platforms:
      - Linux64
    types:
      debug:
        task: tasks/builds/haz_linux.yml
  linux64-shell-haz:
    platforms:
      - Linux64
    types:
      debug:
        task: tasks/builds/haz_shell_linux.yml
  macosx64:
    platforms:
      - MacOSX64
    types:
      opt:
        task: tasks/builds/opt_macosx64.yml
      debug:
        task: tasks/builds/dbg_macosx64.yml
  macosx64-st-an:
    platforms:
      - MacOSX64 Static Analysis
    types:
      opt:
        task: tasks/builds/opt_macosx64_st-an.yml
  sm-plain:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_plain.yml
      debug:
       task: tasks/builds/sm_plaindebug.yml
  sm-arm-sim:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_arm_sim.yml
  sm-arm-sim-osx:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_arm_sim_osx.yml
  sm-compacting:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_compacting.yml
  sm-generational:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_generational.yml
  sm-rootanalysis:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_rootanalysis.yml
  sm-warnaserr:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_warnaserr.yml
      debug:
        task: tasks/builds/sm_warnaserrdebug.yml

post-build:
  upload-symbols:
    allowed_build_tasks:
      - tasks/builds/opt_linux64.yml
      - tasks/builds/opt_linux64_st-an.yml
      - tasks/builds/dbg_linux64.yml
      - tasks/builds/android_api_15.yml
    task: tasks/post-builds/upload_symbols.yml

tests:
  cppunit:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_cppunit_dbg.yml
  crashtest:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_crashtest_dbg.yml
  crashtest-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_crashtest_e10s_dbg.yml
  external-media-tests:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_external_media_tests.yml
  firefox-ui-functional:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_firefox_ui_functional.yml
  firefox-ui-functional-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_firefox_ui_functional_e10s.yml
  gtest:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_gtest_dbg.yml
  jittests:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_jittests_dbg.yml
  jsreftest:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_jsreftest_dbg.yml
  jsreftest-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_jsreftest_e10s_dbg.yml
  marionette:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_x86_kk_opt.yml:
        task: tasks/tests/b2g_emulator_marionette.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_marionette_dbg.yml
  marionette-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_marionette_e10s_dbg.yml
  mochitest:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_x86_l_opt.yml:
        task: tasks/tests/b2g_emulator_mochitest.yml
      tasks/builds/b2g_emulator_x86_kk_opt.yml:
        task: tasks/tests/b2g_emulator_mochitest.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_plain_dbg.yml
  mochitest-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_plain_e10s_dbg.yml
  mochitest-a11y:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_a11y_dbg.yml
  mochitest-browser-chrome:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_bc_dbg.yml
  mochitest-browser-chrome-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_bc_e10s_dbg.yml
  mochitest-chrome:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_chrome_dbg.yml
  mochitest-devtools-chrome:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_dt_dbg.yml
  mochitest-jetpack:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_jetpack_dbg.yml
  mochitest-media:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_media_dbg.yml
  mochitest-media-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_media_e10s_dbg.yml
  mochitest-webgl:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_gl_dbg.yml
  reftest:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_x86_l_opt.yml:
        task: tasks/tests/b2g_emulator_reftest.yml
      tasks/builds/b2g_emulator_x86_kk_opt.yml:
        task: tasks/tests/b2g_emulator_reftest.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_reftest_dbg.yml
  reftest-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_reftest_e10s_dbg.yml
  web-platform-tests:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_dbg.yml
  web-platform-tests-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_e10s_dbg.yml
  web-platform-tests-reftests:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_reftests_dbg.yml
  web-platform-tests-reftests-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_reftests_e10s_dbg.yml
  xpcshell:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_xpcshell_dbg.yml
