/* (c) 2020 KAI OS TECHNOLOGIES (HONG KONG) LIMITED All rights reserved. This
 * file or any portion thereof may not be reproduced or used in any manner
 * whatsoever without the express written permission of KAI OS TECHNOLOGIES
 * (HONG KONG) LIMITED. KaiOS is the trademark of KAI OS TECHNOLOGIES (HONG KONG)
 * LIMITED or its affiliate company and may be registered in some jurisdictions.
 * All other trademarks are the property of their respective owners.
 */

#include "nsIGeolocationProvider.idl"

[scriptable, uuid(59524ca9-fd1a-4d43-8fc2-06054d76d51d)]
interface nsIGeolocationNetworkProvider : nsIGeolocationProvider
{
  /**
   * enable/disable network positioning service of E911
   */
  void setE911(in boolean enable);
};
